### ISSUE TITLE
Application Crashing ... on adding the second project !!!

### ISSUE THREAD

**Issue by aiamuzz** [flathub/org.gottcode.Kapow#1]
Application Crashing ... on adding the second project ... when reopened 2nd project not created !!!

**Comment by gottcode** [comment]
Odd, this doesn't happen for me. What distro are you using?

**Comment by aiamuzz** [comment]
Deepin OS 15.6(Debian based) !!!

You can provide me with any debugging commands that will enable you to probe further ...

**Comment by gottcode** [comment]
I've finally been able to reproduce this and generate a debug trace. Thanks for offering to help, though!

**Comment by gottcode** [comment]
This should now be fixed in version 1.5.7

**Comment by aiamuzz** [comment]
> I've finally been able to reproduce this and generate a debug trace. Thanks for offering to help, though!

no sweat ... anytime .. 
Upgraded ... tested ... confirmed Working !!!
we use it ... repaying you in ways i can afford


:)
